In [1]:
import pandas as pd
pokemon=pd.read_excel(r"C:\Users\Ajay\Desktop\pokemon_data.xlsx")
pokemon

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [2]:
pokemon.set_index("Name")

,#,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,
Bulbasaur,1,Grass,Poison,45,49,49,65,65,45,1,False
Ivysaur,2,Grass,Poison,60,62,63,80,80,60,1,False
Venusaur,3,Grass,Poison,80,82,83,100,100,80,1,False
VenusaurMega Venusaur,3,Grass,Poison,80,100,123,122,120,80,1,False
Charmander,4,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
Diancie,719,Rock,Fairy,50,100,150,100,150,50,6,True
DiancieMega Diancie,719,Rock,Fairy,50,160,110,160,110,110,6,True
HoopaHoopa Confined,720,Psychic,Ghost,80,110,60,150,130,70,6,True
HoopaHoopa Unbound,720,Psychic,Dark,80,160,60,170,130,80,6,True
Volcanion,721,Fire,Water,80,110,120,130,90,70,6,True

In [3]:
pokemon.set_index("Type 1")

,#,Name,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,,
Grass,1,Bulbasaur,Poison,45,49,49,65,65,45,1,False
Grass,2,Ivysaur,Poison,60,62,63,80,80,60,1,False
Grass,3,Venusaur,Poison,80,82,83,100,100,80,1,False
Grass,3,VenusaurMega Venusaur,Poison,80,100,123,122,120,80,1,False
Fire,4,Charmander,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
Rock,719,Diancie,Fairy,50,100,150,100,150,50,6,True
Rock,719,DiancieMega Diancie,Fairy,50,160,110,160,110,110,6,True
Psychic,720,HoopaHoopa Confined,Ghost,80,110,60,150,130,70,6,True
Psychic,720,HoopaHoopa Unbound,Dark,80,160,60,170,130,80,6,True
Fire,721,Volcanion,Water,80,110,120,130,90,70,6,True

In [5]:
pokemon.set_index(["Name","Type 2"])

,,#,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,Type 2,,,,,,,,,,
Bulbasaur,Poison,1,Grass,45,49,49,65,65,45,1,False
Ivysaur,Poison,2,Grass,60,62,63,80,80,60,1,False
Venusaur,Poison,3,Grass,80,82,83,100,100,80,1,False
VenusaurMega Venusaur,Poison,3,Grass,80,100,123,122,120,80,1,False
Charmander,NaN,4,Fire,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
Diancie,Fairy,719,Rock,50,100,150,100,150,50,6,True
DiancieMega Diancie,Fairy,719,Rock,50,160,110,160,110,110,6,True
HoopaHoopa Confined,Ghost,720,Psychic,80,110,60,150,130,70,6,True
HoopaHoopa Unbound,Dark,720,Psychic,80,160,60,170,130,80,6,True
Volcanion,Water,721,Fire,80,110,120,130,90,70,6,True

In [6]:
pokemon.set_index(keys=["Name","Type 2"])

,,#,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,Type 2,,,,,,,,,,
Bulbasaur,Poison,1,Grass,45,49,49,65,65,45,1,False
Ivysaur,Poison,2,Grass,60,62,63,80,80,60,1,False
Venusaur,Poison,3,Grass,80,82,83,100,100,80,1,False
VenusaurMega Venusaur,Poison,3,Grass,80,100,123,122,120,80,1,False
Charmander,NaN,4,Fire,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
Diancie,Fairy,719,Rock,50,100,150,100,150,50,6,True
DiancieMega Diancie,Fairy,719,Rock,50,160,110,160,110,110,6,True
HoopaHoopa Confined,Ghost,720,Psychic,80,110,60,150,130,70,6,True
HoopaHoopa Unbound,Dark,720,Psychic,80,160,60,170,130,80,6,True
Volcanion,Water,721,Fire,80,110,120,130,90,70,6,True

In [7]:
pokemon.sort_index()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [8]:
pokemon.index

RangeIndex(start=0, stop=800, step=1)

In [9]:
type(pokemon.index)

pandas.core.indexes.range.RangeIndex

In [10]:
pokemon.index[0]

0

In [11]:
pokemon.set_index("Name",inplace=True)

In [12]:
pokemon.index[0]

'Bulbasaur'

In [13]:
type(pokemon.index)

pandas.core.indexes.base.Index

In [14]:
pokemon.reset_index()

,Name,#,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,1,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,2,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,3,Grass,Poison,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,3,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,4,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,719,Rock,Fairy,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,719,Rock,Fairy,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,720,Psychic,Ghost,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,720,Psychic,Dark,80,160,60,170,130,80,6,True
799,Volcanion,721,Fire,Water,80,110,120,130,90,70,6,True

In [17]:
pokemon.set_index(keys=["Type 2","Type 1"],inplace=True)

In [18]:
pokemon.index[0]

('Poison', 'Grass')

In [19]:
type(pokemon.index)  # now we used multiple indec so, as a result it shows Multiinddex in output

pandas.core.indexes.multi.MultiIndex

In [20]:
pokemon.index

MultiIndex([('Poison',   'Grass'),
            ('Poison',   'Grass'),
            ('Poison',   'Grass'),
            ('Poison',   'Grass'),
            (     nan,    'Fire'),
            (     nan,    'Fire'),
            ('Flying',    'Fire'),
            ('Dragon',    'Fire'),
            ('Flying',    'Fire'),
            (     nan,   'Water'),
            ...
            ('Dragon',  'Flying'),
            ('Dragon',  'Flying'),
            (     nan,   'Fairy'),
            ('Flying',    'Dark'),
            ('Ground',  'Dragon'),
            ( 'Fairy',    'Rock'),
            ( 'Fairy',    'Rock'),
            ( 'Ghost', 'Psychic'),
            (  'Dark', 'Psychic'),
            ( 'Water',    'Fire')],
           names=['Type 2', 'Type 1'], length=800)

# .index.get_level_values()

In [26]:
# when we have huge data so work with sorting  sort_values()
# now we will fech index 
pokemon.index.get_level_values(0)

Index(['Poison', 'Poison', 'Poison', 'Poison',      nan,      nan, 'Flying',
       'Dragon', 'Flying',      nan,
       ...
       'Dragon', 'Dragon',      nan, 'Flying', 'Ground',  'Fairy',  'Fairy',
        'Ghost',   'Dark',  'Water'],
      dtype='object', name='Type 2', length=800)

In [23]:
pokemon.index.get_level_values(1)

Index(['Grass', 'Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Fire',
       'Fire', 'Water',
       ...
       'Flying', 'Flying', 'Fairy', 'Dark', 'Dragon', 'Rock', 'Rock',
       'Psychic', 'Psychic', 'Fire'],
      dtype='object', name='Type 1', length=800)

In [24]:
pokemon.index.get_level_values("Type 1")

Index(['Grass', 'Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Fire',
       'Fire', 'Water',
       ...
       'Flying', 'Flying', 'Fairy', 'Dark', 'Dragon', 'Rock', 'Rock',
       'Psychic', 'Psychic', 'Fire'],
      dtype='object', name='Type 1', length=800)

In [25]:
pokemon.index.get_level_values("Type 2")

Index(['Poison', 'Poison', 'Poison', 'Poison',      nan,      nan, 'Flying',
       'Dragon', 'Flying',      nan,
       ...
       'Dragon', 'Dragon',      nan, 'Flying', 'Ground',  'Fairy',  'Fairy',
        'Ghost',   'Dark',  'Water'],
      dtype='object', name='Type 2', length=800)

# .index.set_names()

In [28]:
pokemon.index.set_names(["Type 1","Type 23"],inplace=True)

In [29]:
pokemon #3 insex has been changed

                  #  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  \
Type 1 Type 23
Poison Grass      1  45      49       49       65       65     45           1
       Grass      2  60      62       63       80       80     60           1
       Grass      3  80      82       83      100      100     80           1
       Grass      3  80     100      123      122      120     80           1
NaN    Fire       4  39      52       43       60       50     65           1
...             ...  ..     ...      ...      ...      ...    ...         ...
Fairy  Rock     719  50     100      150      100      150     50           6
       Rock     719  50     160      110      160      110    110           6
Ghost  Psychic  720  80     110       60      150      130     70           6
Dark   Psychic  720  80     160       60      170      130     80           6
Water  Fire     721  80     110      120      130       90     70           6

                Legendary
Type 1 Type 23
Poison Grass        False
       Grass        False
       Grass        False
       Grass        False
NaN    Fire         False
...                   ...
Fairy  Rock          True
       Rock          True
Ghost  Psychic       True
Dark   Psychic       True
Water  Fire          True

[800 rows x 9 columns]

# .sort_index()

In [30]:
pokemon.sort_index()  # so basically we have two  index  so , npth od the index will be sort in ascending order

                   #   HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
Type 1 Type 23
Bug    Poison    451   40      50       90       30       55     65
       Rock      347   45      95       50       40       50     75
       Rock      348   75     125      100       70       80     45
Dark   Fighting  675   95     124       78       69       71     58
       Ghost     442   50      92      108       92      108     35
...              ...  ...     ...      ...      ...      ...    ...
NaN    Water     594  165      75       80       40       45     65
       Water     656   41      56       40       62       44     71
       Water     657   54      63       52       83       56     97
       Water     692   50      53       62       58       63     44
       Water     693   71      73       88      120       89     59

                 Generation  Legendary
Type 1 Type 23
Bug    Poison             4      False
       Rock               3      False
       Rock               3      False
Dark   Fighting           6      False
       Ghost              4      False
...                     ...        ...
NaN    Water              5      False
       Water              6      False
       Water              6      False
       Water              6      False
       Water              6      False

[800 rows x 9 columns]

In [31]:
pokemon.sort_index(ascending=[True,False])  # we provide sort index value fasle for Type 23 column

                  #  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  \
Type 1 Type 23
Bug    Rock     347  45      95       50       40       50     75           3
       Rock     348  75     125      100       70       80     45           3
       Poison   451  40      50       90       30       55     65           4
Dark   Water    130  95     155      109       70      130     81           1
       Water    318  45      90       20       65       20     65           3
...             ...  ..     ...      ...      ...      ...    ...         ...
NaN    Bug      588  50      75       45       40       45     60           5
       Bug      616  50      40       85       40       65     25           5
       Bug      617  80      70       40      100       60    145           5
       Bug      664  38      35       40       27       25     35           6
       Bug      665  45      22       60       27       30     29           6

                Legendary
Type 1 Type 23
Bug    Rock         False
       Rock         False
       Poison       False
Dark   Water        False
       Water        False
...                   ...
NaN    Bug          False
       Bug          False
       Bug          False
       Bug          False
       Bug          False

[800 rows x 9 columns]

In [ ]:
# and we see  huge gap in Type 1 , its means Rock, Poison is matched with Bug

# extract rows from multindex

In [36]:
pokemon.loc[("Type 1","Type 23")]  # usually it work ,but it is showing error
#List does not work in it so i used tuple

C:\Users\Ajay\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  """Entry point for launching an IPython kernel.

KeyError: 'Type 1'

In [37]:
pokemon.ix[("Type 1","Type 23")]  # still showing error

C:\Users\Ajay\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
C:\Users\Ajay\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  """Entry point for launching an IPython kernel.

KeyError: 'Type 1'

# .transpose()

In [38]:
pokemon.transpose() # it transpose all data

Type 1     Poison                         NaN        Flying Dragon Flying  \
Type 23     Grass  Grass  Grass  Grass   Fire   Fire   Fire   Fire   Fire
#               1      2      3      3      4      5      6      6      6
HP             45     60     80     80     39     58     78     78     78
Attack         49     62     82    100     52     64     84    130    104
Defense        49     63     83    123     43     58     78    111     78
Sp. Atk        65     80    100    122     60     80    109    130    159
Sp. Def        65     80    100    120     50     65     85     85    115
Speed          45     60     80     80     65     80    100    100    100
Generation      1      1      1      1      1      1      1      1      1
Legendary   False  False  False  False  False  False  False  False  False

Type 1        NaN  ... Dragon          NaN Flying Ground Fairy         Ghost  \
Type 23     Water  ... Flying Flying Fairy   Dark Dragon  Rock  Rock Psychic
#               7  ...    714    715   716    717    718   719   719     720
HP             44  ...     40     85   126    126    108    50    50      80
Attack         48  ...     30     70   131    131    100   100   160     110
Defense        65  ...     35     80    95     95    121   150   110      60
Sp. Atk        50  ...     45     97   131    131     81   100   160     150
Sp. Def        64  ...     40     80    98     98     95   150   110     130
Speed          43  ...     55    123    99     99     95    50   110      70
Generation      1  ...      6      6     6      6      6     6     6       6
Legendary   False  ...  False  False  True   True   True  True  True    True

Type 1        Dark Water
Type 23    Psychic  Fire
#              720   721
HP              80    80
Attack         160   110
Defense         60   120
Sp. Atk        170   130
Sp. Def        130    90
Speed           80    70
Generation       6     6
Legendary     True  True

[9 rows x 800 columns]

# .swaplevel()

In [39]:
pokemon.swaplevel()  # index intercange

                  #  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  \
Type 23 Type 1
Grass   Poison    1  45      49       49       65       65     45           1
        Poison    2  60      62       63       80       80     60           1
        Poison    3  80      82       83      100      100     80           1
        Poison    3  80     100      123      122      120     80           1
Fire    NaN       4  39      52       43       60       50     65           1
...             ...  ..     ...      ...      ...      ...    ...         ...
Rock    Fairy   719  50     100      150      100      150     50           6
        Fairy   719  50     160      110      160      110    110           6
Psychic Ghost   720  80     110       60      150      130     70           6
        Dark    720  80     160       60      170      130     80           6
Fire    Water   721  80     110      120      130       90     70           6

                Legendary
Type 23 Type 1
Grass   Poison      False
        Poison      False
        Poison      False
        Poison      False
Fire    NaN         False
...                   ...
Rock    Fairy        True
        Fairy        True
Psychic Ghost        True
        Dark         True
Fire    Water        True

[800 rows x 9 columns]

# .stack()

In [40]:
pokemon.stack()   # column to rows

Type 1  Type 23
Poison  Grass    #                1
                 HP              45
                 Attack          49
                 Defense         49
                 Sp. Atk         65
                               ...
Water   Fire     Sp. Atk        130
                 Sp. Def         90
                 Speed           70
                 Generation       6
                 Legendary     True
Length: 7200, dtype: object

In [42]:
s=pokemon.stack().to_frame()

In [46]:
s.unstack() # rows to column  
# but it is not working ,i dont know why

ValueError: Index contains duplicate entries, cannot reshape

In [47]:
# i left unstack video , becasue it is not working

ValueError: Index contains duplicate entries, cannot reshape

# .pivot()

In [48]:
pokemon.reset_index()

,Type 1,Type 23,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Poison,Grass,1,45,49,49,65,65,45,1,False
1,Poison,Grass,2,60,62,63,80,80,60,1,False
2,Poison,Grass,3,80,82,83,100,100,80,1,False
3,Poison,Grass,3,80,100,123,122,120,80,1,False
4,NaN,Fire,4,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Fairy,Rock,719,50,100,150,100,150,50,6,True
796,Fairy,Rock,719,50,160,110,160,110,110,6,True
797,Ghost,Psychic,720,80,110,60,150,130,70,6,True
798,Dark,Psychic,720,80,160,60,170,130,80,6,True
799,Water,Fire,721,80,110,120,130,90,70,6,True

In [51]:
pokemon.pivot(index="HP",columns="Attack",values="Speed")   the code is fine bt still giving error

ValueError: Index contains duplicate entries, cannot reshape

In [52]:
pd.melt(pokemon,id_vars="Attack")

      Attack   variable value
0         49          #     1
1         62          #     2
2         82          #     3
3        100          #     3
4         52          #     4
...      ...        ...   ...
6395     100  Legendary  True
6396     160  Legendary  True
6397     110  Legendary  True
6398     160  Legendary  True
6399     110  Legendary  True

[6400 rows x 3 columns]